// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:dd89010a-2ff2-4df4-87e9-56806d893e51",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Hzb8ZFmXY",
    "aws_user_pools_web_client_id": "4jjj7neiflku4v7h514i7k7smd",
    "oauth": {
        "domain": "posdb3e99f0e-b3e99f0e-ac.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost/signin/",
        "redirectSignOut": "http://localhost/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
